*.selected.bg = #1a1a4d
*.selected.fg = white
*.selected.bold = true

msglist_*.selected.fg = white
msglist_*.selected.bg = #1a1a4d

msglist_marked.selected.fg = white
msglist_marked.selected.bg = #1a1a4d

selector_default.fg = white
selector_default.bg = #1a1a4d
selector_focused.fg = white
selector_focused.bg = #1a1a4d
selector_focused.bold = true
selector_chooser.fg = white
selector_chooser.bg = #1a1a4d
selector_chooser.bold = true

title.fg = white
title.bg = #1a1a4d
title.bold = true
stack.fg = white
stack.bg = #1a1a4d

default.selected.fg = white
default.selected.bg = #1a1a4d
default.selected.bold = true
part_*.selected.fg = white
part_*.selected.bg = #1a1a4d
part_filename.selected.bold = true

completion_default.selected.fg = white
completion_default.selected.bg = #1a1a4d
completion_default.selected.bold = true
